from pathlib import Path
import sys
root=Path(sys.argv[1] if len(sys.argv)>1 else 'v1.1/base').resolve();p=root/'core.py';s=p.read_text(encoding='utf-8')

def one(old,new,label):
    global s
    if old not in s:raise SystemExit(f'anchor missing: {label}')
    s=s.replace(old,new,1)

one('''        if op=="add":\n            obj={"id":uid(),"name":args.get("name","Part"),"kind":args.get("kind","box"),"params":args.get("params",{"x":20,"y":20,"z":20}),"material":args.get("material","aluminum_6061_t6"),"transform":args.get("transform",_transform()),"features":deepcopy(args.get("features",[])),"semantic":args.get("semantic",{}),"visible":True}\n''','''        if op=="add":\n            if args.get("kind")=="component":raise ValueError("Purchased components must be instantiated with add_component so registry identity, provenance, interfaces and BOM remain authoritative")\n            obj={"id":uid(),"name":args.get("name","Part"),"kind":args.get("kind","box"),"params":args.get("params",{"x":20,"y":20,"z":20}),"material":args.get("material","aluminum_6061_t6"),"transform":args.get("transform",_transform()),"features":deepcopy(args.get("features",[])),"semantic":args.get("semantic",{}),"visible":True}\n''','generic component bypass')
one('''        elif op=="update":\n            obj=object_by_id(str(args.pop("id"))); changed=obj["id"]\n            for k,v in args.items():\n                if k in {"name","params","material","semantic","visible","component_ref"}: obj[k]=v\n''','''        elif op=="update":\n            obj=object_by_id(str(args.pop("id"))); changed=obj["id"]\n            if obj.get("kind")=="component":\n                forbidden=set(args)&{"params","material","component_ref","component_snapshot","interfaces","features"}\n                if forbidden:raise ValueError("Purchased component engineering data is immutable; use replace_component or explicit sync_component instead of editing "+", ".join(sorted(forbidden)))\n            for k,v in args.items():\n                if k in {"name","params","material","semantic","visible","component_ref"}: obj[k]=v\n''','component immutable update')
one('''        elif op=="transform":\n            obj=object_by_id(str(args.get("id"))); changed=obj["id"]; t=obj.setdefault("transform",_transform())\n            for k in ("position","rotation_deg","scale"):\n                if k in args:t[k]=[float(x) for x in args[k]]\n''','''        elif op=="transform":\n            obj=object_by_id(str(args.get("id"))); changed=obj["id"]; t=obj.setdefault("transform",_transform())\n            if obj.get("kind")=="component" and "scale" in args and any(abs(float(x)-1.0)>1e-9 for x in args["scale"]):raise ValueError("Purchased components cannot be scaled; their physical dimensions are authoritative")\n            for k in ("position","rotation_deg","scale"):\n                if k in args:t[k]=[float(x) for x in args[k]]\n''','component no scaling')
one('''            if old_cid:_component_bom_upsert(str(old_cid),-1)\n            _component_bom_upsert(cid,1);changed=obj["id"]\n''','''            if old_cid:_component_bom_upsert(str(old_cid),-1)\n            _component_bom_upsert(cid,1);PROJECT["bom"][:]=[x for x in PROJECT["bom"] if int(x.get("qty",1) or 0)>0];changed=obj["id"]\n''','replace BOM cleanup')
one('''        elif op=="add_feature":\n            obj=object_by_id(str(args.get("id")));obj.setdefault("features",[]).append(deepcopy(args.get("feature") or {}));changed=obj["id"]\n        elif op=="delete_feature":\n            obj=object_by_id(str(args.get("id")));idx=int(args.get("index",-1));obj["features"].pop(idx);changed=obj["id"]\n''','''        elif op=="add_feature":\n            obj=object_by_id(str(args.get("id")));\n            if obj.get("kind")=="component":raise ValueError("Purchased component geometry cannot receive CAD features. Model machining as a custom/fabricated derivative instead.")\n            obj.setdefault("features",[]).append(deepcopy(args.get("feature") or {}));changed=obj["id"]\n        elif op=="delete_feature":\n            obj=object_by_id(str(args.get("id")));\n            if obj.get("kind")=="component":raise ValueError("Purchased component geometry is immutable")\n            idx=int(args.get("index",-1));obj["features"].pop(idx);changed=obj["id"]\n''','component feature invariants')
p.write_text(s,encoding='utf-8');print('enforced purchased-component invariants')
