from __future__ import annotations
from pathlib import Path
import re, sys

root=Path(sys.argv[1] if len(sys.argv)>1 else 'v1.1/base').resolve()

def edit(path,fn):
    p=root/path;s=p.read_text(encoding='utf-8');n=fn(s)
    if n==s:raise SystemExit(f'No change produced for {path}')
    p.write_text(n,encoding='utf-8')

def one(s,old,new,label):
    if old not in s:raise SystemExit(f'anchor not found: {label}')
    return s.replace(old,new,1)

def patch_core(s):
    s=one(s,'import cadquery as cq\n','import cadquery as cq\nimport component_registry\nimport physical_components\n','core imports')
    s=one(s,'APP_VERSION = "1.0.1"','APP_VERSION = "1.1.0-dev"','version')
    s=one(s,'"schema": 3, "version": APP_VERSION','"schema": 4, "version": APP_VERSION','schema default')
    s=one(s,'"component_ref":"compute.raspberry_pi_5_8gb","code":','"component_ref":"compute.raspberry_pi_5_8gb","component_snapshot":component_registry.component_snapshot("compute.raspberry_pi_5_8gb"),"interfaces":component_registry.component_by_id("compute.raspberry_pi_5_8gb").get("interfaces",[]),"code":','default Pi snapshot')
    s=one(s,'"joints":[], "loads":[], "constraints":[], "requirements":[], "bom":[], "simulations":[], "notebook":[],','"joints":[], "loads":[], "constraints":[], "requirements":[], "bom":[component_registry.bom_item("compute.raspberry_pi_5_8gb")], "connections":[], "simulations":[], "notebook":[],','default BOM/connections')
    s=one(s,'q=deepcopy(p); q.setdefault("schema",3); q.setdefault("version",APP_VERSION); q.setdefault("name","ForgeCAD Project")','q=deepcopy(p); q["schema"]=max(4,int(q.get("schema",0) or 0)); q["version"]=APP_VERSION; q.setdefault("name","ForgeCAD Project")','upgrade schema')
    s=one(s,'for k,default in (("objects",[]),("joints",[]),("loads",[]),("constraints",[]),("requirements",[]),("bom",[]),("simulations",[]),("notebook",[]),("ledger",[])): q.setdefault(k,deepcopy(default))','for k,default in (("objects",[]),("joints",[]),("loads",[]),("constraints",[]),("requirements",[]),("bom",[]),("connections",[]),("simulations",[]),("notebook",[]),("ledger",[])): q.setdefault(k,deepcopy(default))','upgrade connections')
    old='''    for o in q["objects"]:\n        o.setdefault("id",uid());o.setdefault("features",[]);o.setdefault("transform",_transform());o.setdefault("material","aluminum_6061_t6");o.setdefault("semantic",{});o.setdefault("visible",True)\n    return q\n'''
    new='''    for o in q["objects"]:\n        o.setdefault("id",uid());o.setdefault("features",[]);o.setdefault("transform",_transform());o.setdefault("material","aluminum_6061_t6");o.setdefault("semantic",{});o.setdefault("visible",True)\n        if o.get("component_ref"):\n            try:\n                snap=component_registry.component_snapshot(str(o["component_ref"]));o.setdefault("component_snapshot",snap);o.setdefault("interfaces",deepcopy(snap.get("interfaces",[])))\n            except KeyError: pass\n    # Legacy projects did not automatically put purchased component instances in the BOM.\n    bom_refs={x.get("component_ref") for x in q.get("bom",[])}\n    for o in q["objects"]:\n        if o.get("component_ref") and o.get("component_ref") not in bom_refs:\n            try:q["bom"].append(component_registry.bom_item(str(o["component_ref"])))\n            except KeyError:pass\n    return q\n'''
    s=one(s,old,new,'upgrade component snapshots')
    s=re.sub(r'def _component_parts\(obj: dict\[str, Any\]\) -> list\[tuple\[Any,str\]\]\|None:\n    if obj\.get\("component_ref"\)=="compute\.raspberry_pi_5_8gb": return _pi5_local_parts\(\)\n    return None\n', 'def _component_parts(obj: dict[str, Any]) -> list[tuple[Any,str]]|None:\n    # v1.1 resolves every known purchased component through the physical component layer.\n    parts=physical_components.component_parts(obj)\n    return parts if parts else None\n', s, count=1)
    old='''def object_metrics(obj: dict[str, Any]) -> dict[str, Any]:\n    sh=build_shape(obj); bb=sh.BoundingBox(); vol=float(sh.Volume()); mat=MATERIALS.get(obj.get("material"),MATERIALS["aluminum_6061_t6"]); mass=vol*1e-9*float(mat["density_kg_m3"]); c=sh.Center()\n    return {"volume_mm3":vol,"area_mm2":float(sh.Area()),"mass_kg":mass,"bounds_mm":{"x":bb.xlen,"y":bb.ylen,"z":bb.zlen},"centroid_mm":[c.x,c.y,c.z],"material":mat["name"]}\n\ndef project_metrics() -> dict[str, Any]:\n    vals=[object_metrics(o) for o in PROJECT["objects"] if o.get("visible",True)]\n    return {"object_count":len(PROJECT["objects"]),"mass_kg":sum(x["mass_kg"] for x in vals),"bom_cost_usd":sum(float(x.get("unit_cost_usd",0))*float(x.get("qty",1)) for x in PROJECT.get("bom",[])),"active_design":ACTIVE_DESIGN}\n'''
    new='''def object_metrics(obj: dict[str, Any]) -> dict[str, Any]:\n    sh=build_shape(obj); bb=sh.BoundingBox(); vol=float(sh.Volume()); mat=MATERIALS.get(obj.get("material"),MATERIALS["aluminum_6061_t6"]); mass=vol*1e-9*float(mat["density_kg_m3"]); c=sh.Center()\n    if obj.get("kind")=="component":\n        definition=physical_components.component_definition(obj)\n        if definition and definition.get("mass_g") is not None:mass=float(definition["mass_g"])/1000.0\n    return {"volume_mm3":vol,"area_mm2":float(sh.Area()),"mass_kg":mass,"bounds_mm":{"x":bb.xlen,"y":bb.ylen,"z":bb.zlen},"centroid_mm":[c.x,c.y,c.z],"material":mat["name"],"geometry_fidelity":obj.get("component_snapshot",{}).get("geometry",{}).get("fidelity") if obj.get("kind")=="component" else "exact_brep"}\n\ndef project_metrics() -> dict[str, Any]:\n    vals=[object_metrics(o) for o in PROJECT["objects"] if o.get("visible",True)]; purchased=sum(o.get("kind")=="component" for o in PROJECT["objects"]); custom=len(PROJECT["objects"])-purchased\n    return {"object_count":len(PROJECT["objects"]),"purchased_component_count":purchased,"custom_part_count":custom,"connection_count":len(PROJECT.get("connections",[])),"mass_kg":sum(x["mass_kg"] for x in vals),"bom_cost_usd":sum(float(x.get("unit_cost_usd",0) or 0)*float(x.get("qty",1) or 1) for x in PROJECT.get("bom",[])),"active_design":ACTIVE_DESIGN}\n'''
    s=one(s,old,new,'metrics')
    marker='''def execute(op: str, args: dict[str,Any]|None=None, actor: str="human", reason: str="") -> dict[str,Any]:\n'''
    helpers='''def _component_bom_upsert(component_id: str, qty_delta: int=1) -> dict[str,Any]:\n    for item in PROJECT.setdefault("bom",[]):\n        if item.get("component_ref")==component_id:\n            item["qty"]=max(0,int(item.get("qty",0))+int(qty_delta));return item\n    item=component_registry.bom_item(component_id,int(qty_delta));item.setdefault("id",uid());PROJECT["bom"].append(item);return item\n\ndef _component_instance_args(component_id: str, name: str|None=None, transform: dict[str,Any]|None=None) -> dict[str,Any]:\n    args=component_registry.make_project_object(component_id,name=name,transform=transform);args.setdefault("transform",_transform());args.setdefault("features",[]);args.setdefault("visible",True);return args\n\ndef reality_check() -> dict[str,Any]:\n    return physical_components.reality_check(PROJECT)\n\n'''
    if marker not in s:raise SystemExit('execute marker missing')
    s=s.replace(marker,helpers+marker,1)
    s=one(s,'mutation=op not in {"project_name","settings"}','mutation=op not in {"project_name","settings"}','mutation anchor')
    old='''        if op=="add":\n            obj={"id":uid(),"name":args.get("name","Part"),"kind":args.get("kind","box"),"params":args.get("params",{"x":20,"y":20,"z":20}),"material":args.get("material","aluminum_6061_t6"),"transform":args.get("transform",_transform()),"features":deepcopy(args.get("features",[])),"semantic":args.get("semantic",{}),"visible":True}\n            for optional in ("component_ref","code"):\n                if optional in args: obj[optional]=deepcopy(args[optional])\n            PROJECT["objects"].append(obj); changed=obj["id"]\n        elif op=="update":\n'''
    new='''        if op=="add":\n            obj={"id":uid(),"name":args.get("name","Part"),"kind":args.get("kind","box"),"params":args.get("params",{"x":20,"y":20,"z":20}),"material":args.get("material","aluminum_6061_t6"),"transform":args.get("transform",_transform()),"features":deepcopy(args.get("features",[])),"semantic":args.get("semantic",{}),"visible":True}\n            for optional in ("component_ref","component_snapshot","interfaces","code"):\n                if optional in args: obj[optional]=deepcopy(args[optional])\n            PROJECT["objects"].append(obj); changed=obj["id"]\n        elif op=="add_component":\n            cid=str(args.get("component_id") or args.get("id") or "");data=_component_instance_args(cid,args.get("name"),args.get("transform"));obj={"id":uid(),**deepcopy(data)};PROJECT["objects"].append(obj);_component_bom_upsert(cid,1);changed=obj["id"]\n        elif op=="update":\n'''
    s=one(s,old,new,'execute add_component')
    old='''        elif op=="transform":\n            obj=object_by_id(str(args.get("id"))); changed=obj["id"]; t=obj.setdefault("transform",_transform())\n            for k in ("position","rotation_deg","scale"):\n                if k in args:t[k]=[float(x) for x in args[k]]\n        elif op=="delete":\n            oid=str(args.get("id"));PROJECT["objects"][:]=[o for o in PROJECT["objects"] if o["id"]!=oid];changed=oid\n'''
    new='''        elif op=="transform":\n            obj=object_by_id(str(args.get("id"))); changed=obj["id"]; t=obj.setdefault("transform",_transform())\n            for k in ("position","rotation_deg","scale"):\n                if k in args:t[k]=[float(x) for x in args[k]]\n        elif op=="mate_components":\n            source=object_by_id(str(args.get("source_id")));target=object_by_id(str(args.get("target_id")));physical_components.mate_objects(source,target,str(args.get("source_interface")),str(args.get("target_interface")),float(args.get("gap_mm",0)));physical_components.connect_interfaces(PROJECT,source,str(args.get("source_interface")),target,str(args.get("target_interface")),"mechanical");changed=source["id"]\n        elif op=="connect_interfaces":\n            a=object_by_id(str(args.get("a_id")));b=object_by_id(str(args.get("b_id")));physical_components.connect_interfaces(PROJECT,a,str(args.get("a_interface")),b,str(args.get("b_interface")),str(args.get("kind","auto")));changed=None\n        elif op=="disconnect":\n            iid=str(args.get("id"));before=len(PROJECT.setdefault("connections",[]));PROJECT["connections"][:]=[x for x in PROJECT["connections"] if str(x.get("id"))!=iid];\n            if len(PROJECT["connections"])==before:raise KeyError(iid)\n            changed=None\n        elif op=="sync_component":\n            obj=object_by_id(str(args.get("id")));cid=str(obj.get("component_ref") or "");fresh=component_registry.component_snapshot(cid);obj["component_snapshot"]=fresh;obj["interfaces"]=deepcopy(fresh.get("interfaces",[]));dims=fresh.get("dimensions_mm",[20,20,20]);obj["params"].update({"x":float(dims[0]),"y":float(dims[1]),"z":float(dims[2])});obj.setdefault("semantic",{}).update({"geometry_fidelity":fresh.get("geometry",{}).get("fidelity"),"trust_score":fresh.get("trust_score",0)});changed=obj["id"]\n        elif op=="replace_component":\n            obj=object_by_id(str(args.get("id")));old_cid=obj.get("component_ref");cid=str(args.get("component_id"));preserve_transform=deepcopy(obj.get("transform",_transform()));preserve_name=obj.get("name");data=_component_instance_args(cid,args.get("name") or preserve_name,preserve_transform);obj.clear();obj.update({"id":str(args.get("id")),**data});\n            if old_cid:_component_bom_upsert(str(old_cid),-1)\n            _component_bom_upsert(cid,1);changed=obj["id"]\n        elif op=="delete":\n            oid=str(args.get("id"));victim=next((o for o in PROJECT["objects"] if o["id"]==oid),None);PROJECT["objects"][:]=[o for o in PROJECT["objects"] if o["id"]!=oid];PROJECT.setdefault("connections",[])[:]=[x for x in PROJECT["connections"] if x.get("a",{}).get("object_id")!=oid and x.get("b",{}).get("object_id")!=oid];\n            if victim and victim.get("component_ref"):_component_bom_upsert(str(victim["component_ref"]),-1)\n            PROJECT["bom"][:]=[x for x in PROJECT["bom"] if int(x.get("qty",1) or 0)>0];changed=oid\n'''
    s=one(s,old,new,'mating and sync operations')
    return s

edit(Path('core.py'),patch_core)
print('ForgeCAD v1.1 core integration patch applied')
